Neos:
  ContentRepository:
    contentDimensions: {}
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 2
        #structureTree:
          #loadingDepth: 2
    nodeTypes:
      groups:
        'other':
          label: 'Sonstiges'
          position: 100
          collapsed: false